name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    

jobs:

  build:
    runs-on: windows-latest
    env:
      ProjectUnitTests:   '${{ github.workspace }}\tests\Unity.Tests\Tests.Unit.csproj'
      PackageProjectPath: '${{ github.workspace }}\src\Unity.Container.csproj'
      PackageOutputPath:  '${{ github.workspace }}\package'

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master        

    - name: Setup local NuGet source
      run: |
        nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
        nuget setApiKey ${{secrets.GITHUB_TOKEN}}

    - name: Add GitVersion and SourceLink
      run: | 
        dotnet add ${{ env.PackageProjectPath }} package GitVersionTask              --no-restore
        dotnet add ${{ env.PackageProjectPath }} package Microsoft.SourceLink.GitHub --no-restore

    - name: Build
      run: | 
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ env.PackageProjectPath }}
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ env.ProjectUnitTests }}

    - name: Test
      run: | 
        dotnet test ${{ env.ProjectUnitTests }}

    - name: Publish Local Package
      run: |
        nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github
