name:  Continuous Deployment

on:
  push:
    branches:
      - 'develop'
      - 'hotfix/**'    
      - 'release/**'    
    # paths:
    #   - 'src/**'

jobs:

  build-deploy:
    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master        

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-preview.8.20363.2'

    - name: Add GitVersion and SourceLink
      run: | 
        dotnet add src/Unity.Abstractions.csproj package GitVersionTask --no-restore --version 5.3.5
        dotnet add src/Unity.Abstractions.csproj package Microsoft.SourceLink.GitHub

    - name: Build
      run: | 
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True src
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj

    - name: Test
      run: | 
        dotnet test ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj

    - name: Publish Local Package
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github
