name: Regression Tests
# https://dotnet.microsoft.com/download/dotnet-core
# https://dotnet.microsoft.com/download/dotnet-framework

on:

  push:
    paths:
      - 'src/**'
      - 'tests/**'
#      - '.github/**'

  pull_request:
    branches:
      - master
      - develop
      - 'hotfix/**'    
      - 'release/**'

jobs:
  build:
    runs-on: windows-latest
    env:
      PackageVersion: '0.0.0'
      UpdateVersionProperties: 'false'
      PackageOutputPath: '${{ github.workspace }}/package'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-preview.8.20363.2'

    - name: Cache
      id: unity-abstractions
      uses: actions/cache@v1
      with:
        path: '${{ github.workspace }}/package'
        key: ${{ github.sha }}

    - name: Build Package
      run: dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True src


  net:
    needs: [ Build ]
    strategy:
      matrix:
        framework: ['net50', 'net48', 'net47', 'net46', 'net45']
    runs-on:  windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-preview.8.20363.2'

    - name: Cache
      id: unity-abstractions
      uses: actions/cache@v1
      with:
        path: '${{ github.workspace }}/package'
        key: ${{ github.sha }}

    - name: Build Package
      env:
        TargetFramework: ${{ matrix.framework }}
      run: |
        dotnet remove ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj reference "..\src\Unity.Abstractions.csproj"
        dotnet add ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj package --source '${{ github.workspace }}/package' Unity.Abstractions --version 0.0.0
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj

    - name: Test
      env:
        TargetFramework: ${{ matrix.framework }}
      run: dotnet test ${{ github.workspace }}/tests/bin/Release/${{ matrix.framework }}/Unity.Abstractions.Tests.dll


  core-2:
    needs: [ Build ]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on:  ${{ matrix.os }}
    env:
      TargetFramework: netcoreapp2.1

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.806'

    - name: Install Nuget
      uses: nuget/setup-nuget@v1

    - name: Cache
      id: unity-abstractions
      uses: actions/cache@v1
      with:
        path: '${{ github.workspace }}/package'
        key: ${{ github.sha }}

    - name: Build Package
      run: |
        nuget add ${{ github.workspace }}/package/Unity.Abstractions.0.0.0.nupkg -Source packages
        dotnet remove ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj reference "..\src\Unity.Abstractions.csproj"
        dotnet add ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj package --source packages Unity.Abstractions --version 0.0.0
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj

    - name: Test
      run: dotnet vstest ${{ github.workspace }}/tests/bin/Release/netcoreapp2.1/Unity.Abstractions.Tests.dll


  core-3:
    needs: [ Build ]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on:  ${{ matrix.os }}
    env:
      TargetFramework: netcoreapp3.1

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.300'

    - name: Cache
      id: unity-abstractions
      uses: actions/cache@v1
      with:
        path: '${{ github.workspace }}/package'
        key: ${{ github.sha }}

    - name: Build Package
      run: |
        dotnet remove ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj reference "..\src\Unity.Abstractions.csproj"
        dotnet add ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj package --source '${{ github.workspace }}/package' Unity.Abstractions --version 0.0.0
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}/tests/Unity.Abstractions.Tests.csproj

    - name: Test
      run: dotnet vstest ${{ github.workspace }}/tests/bin/Release/netcoreapp3.1/Unity.Abstractions.Tests.dll


  uap-10:
    needs: [ Build ]
    runs-on:  windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      id: unity-abstractions
      uses: actions/cache@v1
      with:
        path: '${{ github.workspace }}/package'
        key: ${{ github.sha }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build Tests
      run: msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}/tests/Unity.Abstractions.UWP.csproj

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Test
      run: vstest.console.exe tests\bin\x86\Release\Unity.Abstractions.UWP.build.appxrecipe /framework:FrameworkUap10
