name: Regression Tests
# https://dotnet.microsoft.com/download/dotnet-core
# https://dotnet.microsoft.com/download/dotnet-framework

on: [push]

jobs:

  UWP:
    # needs: [ Build ]
    runs-on:  windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      id: unity-abstractions
      uses: actions/cache@v1
      with:
        path: '${{ github.workspace }}/package'
        # key: ${{ github.sha }}
        key: '748e5364551fc1f798b35eb42f9a35bb77b08c76'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build Package
      run: |
        msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}/tests/Unity.Abstractions.UWP.csproj

    - name: Test
      run: dotnet test ${{ github.workspace }}/tests/bin/Release
